apiVersion: apps/v1
kind: Deployment
metadata:
  name: authservice
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authservice
  template:
    metadata:
      labels:
        app: authservice
    spec:
      containers:
      - name: authservice
        image: cr.yandex/crpqhm9qhte79o09rkl7/x-bank/authenticationservice:develop
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: auth-config
      imagePullSecrets:
        - name:  yandex