apiVersion: v1
kind: Service
metadata:
  name: authservice
  namespace: dev
spec:
  selector:
    app: authservice
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: authservice
  namespace: dev
spec:
  selector:
    app: authservice
  ports:
    - protocol: TCP
      port: 8100
      targetPort: 8080
      nodePort: 30100
  type: NodePort