spring:
  application:
    name: apiGateway
  data:
    redis:
      host: redis
      port: 6379
jwt:
  secret: $2a$09$mk2pVckrnm0t80Pu4vsa6eEcy9Jm6DvGUNAJC1E/TMiO7QBoZZk/y
  access:
    token:
      expiration: 300000
  refresh:
    token:
      expiration: 86400000
webclient:
  base-url: http://auth-service:8080