version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: authservice
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - app-network

#  app:
#    image: authenticationservice:latest
#    build: .
#    ports:
#      - "8888:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/authservice
#      SPRING_DATASOURCE_USERNAME: admin
#      SPRING_DATASOURCE_PASSWORD: admin
#      SPRING_DATA_REDIS_HOST: redis-stack
#      SPRING_DATA_REDIS_PORT: 6379
#    depends_on:
#      - db
#      - redis-stack
#    networks:
#      - app-network

networks:
  app-network:
    driver: bridge

